name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-13 ]
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10' 
      - uses: fortran-lang/setup-fortran@v1
        if: runner.os == 'macOS'
        with:
          compiler: gcc
          version: 13
      - run: |
          make
          make run
